sudo: required
dist: trusty
language: node_js
node_js:
  - "4" 
  - "5"
  - "6"
before_script:
   - ./ci.sh
script:
   - make
after_script:
   - PIDD=`ps -x | grep "json-server" | cut -d' ' -f1 | head -n 1`
   - kill -9 $PIDD
notifications:
  irc: "irc.freenode.org#brass-monkey"
branches:
  only:
    - master