sudo: required
dist: trusty
language: node_js
node_js:
  - "4" 
  - "5"
  - "6"
before_script:
   - npm install -g coveralls 
   - ./ci.sh
script:
   - make
after_script:
   - PIDD=`ps -x | grep "json-server" | cut -d' ' -f1 | head -n 1`
   - kill -9 $PIDD
branches:
  only:
    - master
after_success:
  - cat ./coverage/lcov.info | coveralls