sudo: required
dist: trusty
language: node_js
node_js:
  - "5"
  - "6"
before_script:
   - npm install -g json-server
   - json-server --watch test/fixtures/db.json
script:
   - make ci
after_script:
   - ./build/stop-server.sh
notifications:
  irc: "irc.freenode.org#brass-monkey"
branches:
  only:
    - master
